dist: xenial

sudo: true

language:
  - c

addons:
  apt:
    packages:
      - build-essential
      - doxygen
      - git
      - curl
      - python-serial
      - srecord
      - rlwrap

script:
  - sudo sh .scripts/install-arm-ltd-toolchain.sh
  # the simplelink target supports 802.15.4 out of the box but uses an older set of SDK APIs
  - make -C examples/hello-world -j`nproc --all` TARGET=simplelink BOARD=${CONTIKI_BOARD}
  # the cc26x0-cc13x0 target supports BLE out of the box but uses a newer set of SDK APIs
  - make -C examples/platform-specific/cc26x0-cc13x0/ble-ipv6 -j`nproc --all` TARGET=cc26x0-cc13x0 BOARD=${CONTIKI_BOARD}

env:
  global:
    - CONTIKI_BOARD="launchpad/cc1352r1"
    - ARMLTD_TC_VER="8-2018-q4"
    - ARMLTD_TC_VERDIR="8-2018q4"
    - ARMLTD_TC_SEVERITY="major"
    - ARMLTD_TC_OS="linux"
    - ARMLTD_TC_ARCHIVE=".tar.bz2"
    - PATH="/opt/arm/gcc-arm-none-eabi-${ARMLTD_TC_VER}-${ARMLTD_TC_SEVERITY}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

notifications:
  email: false

#deploy:
#  - provider: releases
#    api_key: "${GH_TOKEN}"
#    file:
#      - foo.tar.xz
#    skip_cleanup: true
#    on:
#      tags: true
